                                                                                                                                                                                                                                                                                                                                                   
#                                                   dddddddd                                                                                                                                                                                                                                                                                        
#                                                   d::::::d                                                         NNNNNNNN        NNNNNNNN                         tttt                                        CCCCCCCCCCCCC                                                               iiii  lllllll                                         
#                                                   d::::::d                                                         N:::::::N       N::::::N                      ttt:::t                                     CCC::::::::::::C                                                              i::::i l:::::l                                         
#                                                   d::::::d                                                         N::::::::N      N::::::N                      t:::::t                                   CC:::::::::::::::C                                                               iiii  l:::::l                                         
#                                                   d:::::d                                                          N:::::::::N     N::::::N                      t:::::t                                  C:::::CCCCCCCC::::C                                                                     l:::::l                                         
#ppppp   pppppppppyyyyyyy           yyyyyyy ddddddddd:::::d     eeeeeeeeeeee        eeeeeeeeeeee    zzzzzzzzzzzzzzzzzN::::::::::N    N::::::Nuuuuuu    uuuuuuttttttt:::::ttttttt        ssssssssss         C:::::C       CCCCCC   ooooooooooo      mmmmmmm    mmmmmmm   ppppp   ppppppppp   iiiiiii  l::::l     eeeeeeeeeeee    rrrrr   rrrrrrrrr   
#3p::::ppp:::::::::py:::::y         y:::::ydd::::::::::::::d   ee::::::::::::ee    ee::::::::::::ee  z:::::::::::::::zN:::::::::::N   N::::::Nu::::u    u::::ut:::::::::::::::::t      ss::::::::::s       C:::::C               oo:::::::::::oo  mm:::::::m  m:::::::mm p::::ppp:::::::::p  i:::::i  l::::l   ee::::::::::::ee  r::::rrr:::::::::r  
#p:::::::::::::::::py:::::y       y:::::yd::::::::::::::::d  e::::::eeeee:::::ee e::::::eeeee:::::eez::::::::::::::z N:::::::N::::N  N::::::Nu::::u    u::::ut:::::::::::::::::t    ss:::::::::::::s      C:::::C              o:::::::::::::::om::::::::::mm::::::::::mp:::::::::::::::::p  i::::i  l::::l  e::::::eeeee:::::eer:::::::::::::::::r 
#pp::::::ppppp::::::py:::::y     y:::::yd:::::::ddddd:::::d e::::::e     e:::::ee::::::e     e:::::ezzzzzzzz::::::z  N::::::N N::::N N::::::Nu::::u    u::::utttttt:::::::tttttt    s::::::ssss:::::s     C:::::C              o:::::ooooo:::::om::::::::::::::::::::::mpp::::::ppppp::::::p i::::i  l::::l e::::::e     e:::::err::::::rrrrr::::::r
# p:::::p     p:::::p y:::::y   y:::::y d::::::d    d:::::d e:::::::eeeee::::::ee:::::::eeeee::::::e      z::::::z   N::::::N  N::::N:::::::Nu::::u    u::::u      t:::::t           s:::::s  ssssss      C:::::C              o::::o     o::::om:::::mmm::::::mmm:::::m p:::::p     p:::::p i::::i  l::::l e:::::::eeeee::::::e r:::::r     r:::::r
# p:::::p     p:::::p  y:::::y y:::::y  d:::::d     d:::::d e:::::::::::::::::e e:::::::::::::::::e      z::::::z    N::::::N   N:::::::::::Nu::::u    u::::u      t:::::t             s::::::s           C:::::C              o::::o     o::::om::::m   m::::m   m::::m p:::::p     p:::::p i::::i  l::::l e:::::::::::::::::e  r:::::r     rrrrrrr
# p:::::p     p:::::p   y:::::y:::::y   d:::::d     d:::::d e::::::eeeeeeeeeee  e::::::eeeeeeeeeee      z::::::z     N::::::N    N::::::::::Nu::::u    u::::u      t:::::t                s::::::s        C:::::C              o::::o     o::::om::::m   m::::m   m::::m p:::::p     p:::::p i::::i  l::::l e::::::eeeeeeeeeee   r:::::r            
# p:::::p    p::::::p    y:::::::::y    d:::::d     d:::::d e:::::::e           e:::::::e              z::::::z      N::::::N     N:::::::::Nu:::::uuuu:::::u      t:::::t    ttttttssssss   s:::::s       C:::::C       CCCCCCo::::o     o::::om::::m   m::::m   m::::m p:::::p    p::::::p i::::i  l::::l e:::::::e            r:::::r            
# p:::::ppppp:::::::p     y:::::::y     d::::::ddddd::::::dde::::::::e          e::::::::e            z::::::zzzzzzzzN::::::N      N::::::::Nu:::::::::::::::uu    t::::::tttt:::::ts:::::ssss::::::s       C:::::CCCCCCCC::::Co:::::ooooo:::::om::::m   m::::m   m::::m p:::::ppppp:::::::pi::::::il::::::le::::::::e           r:::::r            
# p::::::::::::::::p       y:::::y       d:::::::::::::::::d e::::::::eeeeeeee   e::::::::eeeeeeee   z::::::::::::::zN::::::N       N:::::::N u:::::::::::::::u    tt::::::::::::::ts::::::::::::::s         CC:::::::::::::::Co:::::::::::::::om::::m   m::::m   m::::m p::::::::::::::::p i::::::il::::::l e::::::::eeeeeeee   r:::::r            
# p::::::::::::::pp       y:::::y         d:::::::::ddd::::d  ee:::::::::::::e    ee:::::::::::::e  z:::::::::::::::zN::::::N        N::::::N  uu::::::::uu:::u      tt:::::::::::tt s:::::::::::ss            CCC::::::::::::C oo:::::::::::oo m::::m   m::::m   m::::m p::::::::::::::pp  i::::::il::::::l  ee:::::::::::::e   r:::::r            
# p::::::pppppppp        y:::::y           ddddddddd   ddddd    eeeeeeeeeeeeee      eeeeeeeeeeeeee  zzzzzzzzzzzzzzzzzNNNNNNNN         NNNNNNN    uuuuuuuu  uuuu        ttttttttttt    sssssssssss                 CCCCCCCCCCCCC   ooooooooooo   mmmmmm   mmmmmm   mmmmmm p::::::pppppppp    iiiiiiiillllllll    eeeeeeeeeeeeee   rrrrrrr            
# p:::::p               y:::::y                                                                                                                                                                                                                                          p:::::p                                                                    
# p:::::p              y:::::y                                                                                                                                                                                                                                           p:::::p                                                                    
#p:::::::p            y:::::y                                                                                                                                                                                                                                           p:::::::p                                                                   
#p:::::::p           y:::::y                                                                                                                                                                                                                                            p:::::::p                                                                   
#p:::::::p          yyyyyyy                                                                                                                                                                                                                                             p:::::::p                                                                   
#ppppppppp        
# 
# I got bored                                                                                                                                                                                                                                                      ppppppppp      